package com.aowin.mapper;


import com.aowin.domain.Page;
import com.aowin.domain.ScmUser;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.List;
import java.util.Map;

public interface ScmUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scmuser
     *
     * @mbggenerated Thu Nov 24 09:31:10 CST 2022
     */
    int deleteByPrimaryKey(String account);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scmuser
     *
     * @mbggenerated Thu Nov 24 09:31:10 CST 2022
     */
    int insert(ScmUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scmuser
     *
     * @mbggenerated Thu Nov 24 09:31:10 CST 2022
     */
    int insertSelective(ScmUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scmuser
     *
     * @mbggenerated Thu Nov 24 09:31:10 CST 2022
     */
    ScmUser selectByPrimaryKey(String account);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scmuser
     *
     * @mbggenerated Thu Nov 24 09:31:10 CST 2022
     */
    int updateByPrimaryKeySelective(ScmUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scmuser
     *
     * @mbggenerated Thu Nov 24 09:31:10 CST 2022
     */
    int updateByPrimaryKey(ScmUser record);

    //用户登录
    ScmUser queryUserByActAndPwd(Map<String,Object> map);

    //查询数据，模糊查询及分页
    int getScmUsersCount(@Param("scmUser") ScmUser scmUser);
    List<ScmUser> queryUsersByPage(@Param("page") Page<ScmUser> page,@Param("scmUser") ScmUser scmUser);

    //删除用户modelname
    int delUserModelByAccount(String account);
    //删除用户
    int delUserByAccount(String account);

    //新增验证用户
    ScmUser checkScmUser(String account);
    //添加用户
    int insertScmUser(ScmUser scmUser);
    int insertModelName(@Param("account") String account,@Param("modelName")  String modelName);

    int updateScmUser(ScmUser scmUser);

    int updateModelName(@Param("modelname") String modelName, @Param("account")String account);
    int updateModelCode(@Param("modelcode") int modelCode, @Param("account")String account,@Param("oldaccount")String oldAccount);
}